// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVEkeSW2GAjOjL4fJiLOaqmRcNHnPddc',
    appId: '1:594412778710:web:cf81ebbf342ffe07198577',
    messagingSenderId: '594412778710',
    projectId: 'chatappveenay',
    authDomain: 'chatappveenay.firebaseapp.com',
    storageBucket: 'chatappveenay.appspot.com',
    measurementId: 'G-W2L8KV44N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7yLRkkRtnX5V-qjEzPFRYHP8F8oxsAFo',
    appId: '1:594412778710:android:e8afb0565be22bba198577',
    messagingSenderId: '594412778710',
    projectId: 'chatappveenay',
    storageBucket: 'chatappveenay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BeIXSKHFOcg25Wn0Hmc89zxn1e1sadI',
    appId: '1:594412778710:ios:b429b6bdcdabe60f198577',
    messagingSenderId: '594412778710',
    projectId: 'chatappveenay',
    storageBucket: 'chatappveenay.appspot.com',
    iosBundleId: 'com.example.sampleChatApp',
  );
}
